version: "3.5"

services:
    website:
        container_name: rsgenera-front
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8085:80"
        volumes:
            - .:/usr/src/app
